name: Deploy Hugo Website to Plesk

on:
  push:
    branches:
      - main  # Der Workflow wird ausgelöst, wenn auf den Branch `main` gepusht wird

jobs:
  build-and-deploy:
    name: Build and Deploy Hugo Website
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout des Codes
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Installiere Hugo Extended
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      # 3. Baue die Hugo-Website
      - name: Build Hugo Website
        run: hugo

      # 4. Bereite den SSH-Key für das Deployment vor
      - name: Add SSH key
        run: |
          echo "Adding SSH key"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 212.227.161.13 >> ~/.ssh/known_hosts
        shell: bash

      # 5. Deployment via SCP
      - name: Deploy to Server via SCP
        run: scp -r -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ./public/* root@212.227.161.13:/var/www/vhosts/lucky-dice-design.com/httpdocs/
